version: '3'
services:
  goda-discovery-server:
    image: goda-discovery-server
    build: ./goda-discovery-server
    ports:
      - "8761:8761"
  goda-gateway-service:
    image: goda-gateway-service
    build: ./goda-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - goda-discovery-server
  goda-user-profile-service:
    image: goda-user-profile-service
    build: ./goda-user-profile-service
    ports:
      - "8081:8081"
    depends_on:
      - goda-discovery-server
  # goda-social-media-service:
  #   image: goda-social-media-service
  #   build: ./goda-social-media-service
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - goda-discovery-server